# Generated by Django 4.1.2 on 2022-10-21 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('star_wars_universe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='planet',
            new_name='planet_id',
        ),
    ]
